"""Generate the small synthetic data files documented in this directory.

The examples in ``examples/`` synthesize their data in-process and need
no files at all. This script exists for the other case: when you want a
*file* on disk in one of the two formats the readers and the batch
pipeline consume, either to try the I/O path or to see the layout of a
map before pointing the pipeline at your own measurement.

Everything written here is synthetic (a Si 2p metal/oxide doublet pair)
and fully determined by ``SEED`` — regenerating gives byte-identical
output, which is what ``--check`` verifies for the committed text file.

Run from the repository root::

    python examples/data/make_example_data.py            # write files
    python examples/data/make_example_data.py --check    # verify only

Writes ``si2p_single.txt`` (committed) and ``si2p_map_8x8.h5``
(generated on demand, git-ignored).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

from toyomacro.voigtfit import voigt_profile

HERE = Path(__file__).parent
TXT_PATH = HERE / "si2p_single.txt"
H5_PATH = HERE / "si2p_map_8x8.h5"

SEED = 0
ENERGY = np.arange(96.0, 108.01, 0.08)  # eV, binding energy

# Si 2p: metallic Si and SiO2, each a 2p3/2 / 2p1/2 spin-orbit doublet.
# (center_eV, area, fwhm_g_eV) for the 2p3/2 line of each state.
SO_SPLIT = 0.61  # eV, 2p1/2 - 2p3/2
BRANCH = 0.5  # 2p1/2 / 2p3/2 area ratio (degeneracy 2:4)
GAMMA = 0.05  # eV, Lorentzian HWHM
STATES = (
    ("Si0", 99.30, 12000.0, 0.42),
    ("Si4+", 103.40, 7000.0, 0.72),
)


def _spectrum(scale: dict[str, float]) -> np.ndarray:
    """Noise-free Si 2p spectrum with per-state area scaling."""
    y = np.zeros_like(ENERGY)
    for name, center, area, fwhm_g in STATES:
        sigma = fwhm_g / (2.0 * np.sqrt(2.0 * np.log(2.0)))
        a = area * scale.get(name, 1.0)
        y += a * voigt_profile(ENERGY, center, sigma, GAMMA)
        y += a * BRANCH * voigt_profile(
            ENERGY, center + SO_SPLIT, sigma, GAMMA)
    return y + 250.0  # flat inelastic background floor


def build_single() -> np.ndarray:
    """(n_energy, 2) energy/intensity array — Poisson counts."""
    rng = np.random.default_rng(SEED)
    return np.column_stack(
        [ENERGY, rng.poisson(_spectrum({})).astype(np.float64)])


def build_map(n: int = 8) -> np.ndarray:
    """``specdata`` layout: row 0 energy, rows 1.. one spectrum per pixel.

    Oxide fraction ramps left-to-right so the map has visible structure;
    pixel order is row-major over an ``n x n`` grid.
    """
    rng = np.random.default_rng(SEED + 1)
    rows = [ENERGY]
    for iy in range(n):
        for ix in range(n):
            f = ix / (n - 1)  # oxide fraction across the fast axis
            clean = _spectrum({"Si0": 1.0 - 0.9 * f, "Si4+": 0.1 + 0.9 * f})
            rows.append(rng.poisson(clean).astype(np.float32))
    return np.asarray(rows, dtype=np.float32)


def write_txt(path: Path) -> None:
    np.savetxt(
        path, build_single(), fmt=["%.2f", "%.0f"], delimiter="\t",
        header=(
            "Synthetic Si 2p spectrum (Si0 + Si4+ spin-orbit doublets,\n"
            "Poisson counts on a flat background). Generated by\n"
            "examples/data/make_example_data.py -- not a measurement.\n"
            "BE\n"
            "energy_eV\tintensity_counts"),
    )


def write_h5(path: Path) -> None:
    import h5py

    with h5py.File(path, "w") as f:
        d = f.create_dataset("specdata", data=build_map())
        d.attrs["element"] = "Si"
        d.attrs["orbital"] = "2p"
        d.attrs["energy_type"] = "BE"
        d.attrs["source"] = "synthetic"
        d.attrs["license"] = "MIT (same as this repository)"
        d.attrs["generator"] = "examples/data/make_example_data.py"


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--check", action="store_true",
                   help="verify the committed text file reproduces "
                        "exactly, write nothing")
    args = p.parse_args()

    if args.check:
        if not TXT_PATH.exists():
            print(f"missing: {TXT_PATH}")
            return 1
        import tempfile
        with tempfile.TemporaryDirectory() as tmp:
            fresh = Path(tmp) / TXT_PATH.name
            write_txt(fresh)
            ok = fresh.read_bytes() == TXT_PATH.read_bytes()
        print(f"{'OK  ' if ok else 'DIFF'} {TXT_PATH.name} "
              f"{'reproduces exactly' if ok else 'does NOT reproduce'}")
        return 0 if ok else 1

    write_txt(TXT_PATH)
    print(f"wrote {TXT_PATH}  ({ENERGY.size} points, 2 columns)")
    write_h5(H5_PATH)
    print(f"wrote {H5_PATH}  (64 pixels x {ENERGY.size} channels + "
          f"energy row)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
